### ISSUE TITLE
[github] request review event type error

### ISSUE THREAD

**Issue by pd4d10** [git-touch/git-touch#248]
![simulator_screenshot_46A65892-BD9B-4D5C-9BEC-33494EF7C339](https://user-images.githubusercontent.com/9524411/121930948-92a3ad00-cd75-11eb-86ba-e51070bc0167.png)

**Comment by shreyas1599** [comment]
@pd4d10 

It can be fixed by removing the typecasts in https://github.com/git-touch/git-touch/blob/ddfa9e469e5be888aef32b8b13fa09dac079f69c/lib/widgets/timeline_item.dart#L445 and https://github.com/git-touch/git-touch/blob/ddfa9e469e5be888aef32b8b13fa09dac079f69c/lib/widgets/timeline_item.dart#L456

Is there any specific reason why you've used typecasts? If typecasting is necessary then https://github.com/git-touch/git-touch/blob/ddfa9e469e5be888aef32b8b13fa09dac079f69c/lib/widgets/timeline_item.dart#L456 will have to be modified to `GIssueData_repository_issueOrPullRequest__asPullRequest_timelineItems_nodes__asReviewRequestedEvent_requestedReviewer__asUser` as the cast. I'll add a fix based on which you suggest is better

**Comment by pd4d10** [comment]
Yeah, I guess it's just an issue of type. It should be enough to just correct the type (and make sure it doesn't break other places, of course)
