### ISSUE TITLE
restructure screens directory

### ISSUE THREAD

**Issue by shreyas1599** [git-touch/git-touch#92]
I understand that the prefixes `gh`, `bb`, `gt` and `gl` were used to easily identify the files in the screens directory. Still, I find it very cluttered and difficult to access the right file. I think we should add subfolders for each platform. 

@pd4d10 What is your opinion? I'll do this if you are alright with it. I'll have to change all the affected imports.

**Comment by pd4d10** [comment]
Personally I prefer to keep it as is, which would be beneficial for quick searching. Take VSCode as example, if we'd like to search the file GitHub user screen, we could just press `Cmd + P`, and then quickly search it by `gh_user` instead of verbose `github/user` (`user` is not enough because there are several `user`). 

Anyway, there efforts are highly appreciated! Let's keep this issue open for more discussion

**Comment by shreyas1599** [comment]
Closing this. Easier to use `Cmd + P` with `gh`. Been using it since you made the suggestion.
